services:
  - type: web
    name: enterprise-dashboard
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 10 